version: '3.8'

services:
  app:
    build:
      context: .
    container_name: product-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  db:
    image: postgres
    container_name: product-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge