global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8080']

  - job_name: 'app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-app:8080']

